### ISSUE TITLE
Add an info banner when it's needed

### ISSUE THREAD

**Issue by sembrestels** [TECommons/tec-interface#3]
You can copy [this banner](https://github.com/aragon/conviction-funding-pilot/blob/master/src/components/ConvictionBanner.js) from Aragon Conviction Funding pilot and put it [above the layout](https://github.com/aragon/conviction-funding-pilot/blob/8bef50b6d77b254072c7b98efe260d29fb0db137/src/components/MainView.js#L35). Then you can add a `banner.js` file in the [base directory](https://github.com/TECommons/tec-interface/tree/master/src/base), with:

```js
export default {
  text: 'This is a demo of Conviction Voting within the Token Engineering Commons',
  action: 'Learn more',
  link: 'https://twitter.com/tecmns/status/1322262661292122112',
}
```
The button should not appear if `action` or `link` are empty, and the banner itself should not appear if the `banner.js` exports an empty file.

**Comment by anthonyoliai** [comment]
Working on this 👍

**Comment by vivianedias** [comment]
needs to be closed! @sembrestels
